name: build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:
  build:
    env:
       PROJECT_NAME: 'StereoDB.Cluster'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: dotnet restore StereoDB.sln
    - name: Build
      run: dotnet build $(PROJECT_NAME).sln --no-restore
    - name: Test
      run: | 
        docker-compose up -d && sleep 5
        dotnet test tests/$(PROJECT_NAME).Tests/$(PROJECT_NAME).Tests.fsproj --configuration Release --verbosity normal
